### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by comporell** [1IoT/nativescript-connectivity-manager-plugin#8]
Hello, thank you for this great plugin.

Could you add it a functionality to enable/disable Wi-Fi?

Best Regards,

**Comment by chtinnes** [comment]
Hi @comporell,

If you like, you can create a pull request for this feature. 
For Android:
To find out if WiFi is enabled, you can use:
https://developer.android.com/reference/android/net/wifi/WifiManager#isWifiEnabled()

To enable WiFI for API Level 29, see this link:
https://stackoverflow.com/questions/9871762/android-turning-on-wifi-programmatically

For Android >Q enabling WiFi programmatically has been disabled. But you can redirect the app user to the WiFi settings as described here:
https://stackoverflow.com/questions/58075918/is-it-possible-to-programmatically-enable-wifi-on-android-10-devices

**Comment by comporell** [comment]
> For Android >Q enabling WiFi programmatically has been disabled. But you can redirect the app user to the WiFi settings as described here:
> https://stackoverflow.com/questions/58075918/is-it-possible-to-programmatically-enable-wifi-on-android-10-devices

After reading this, I decided to change the workflow. Needed a subscribe for your isWifiEnabled() and a simple setTimeout() did the trick. Thanks for the heads up. Keep up the good work
